//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaTroDBFirstVer1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertise
    {
        public int AdID { get; set; }
        public string Title { get; set; }
        public string URL { get; set; }
        public string Image { get; set; }
        public int AdminID { get; set; }
    
        public virtual User User { get; set; }
    }
}
