//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaTroDBFirstVer1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NhaTroEntities : DbContext
    {
        public NhaTroEntities()
            : base("name=NhaTroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Advertise> Advertise { get; set; }
        public DbSet<Comment> Comment { get; set; }
        public DbSet<Room> Room { get; set; }
        public DbSet<RoomStatus> RoomStatus { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<QLHoTro> QLHoTroes { get; set; }
        public DbSet<QLTDD> QLTDDs { get; set; }
    }
}
