//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaTroDBFirstVer1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLHoTro
    {
        public int HoTroID { get; set; }
        public string QLHoTro1 { get; set; }
        public Nullable<int> AdminID { get; set; }
        public string Currents { get; set; }
    
        public virtual User User { get; set; }
    }
}
