//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaTroDBFirstVer1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Advertise = new HashSet<Advertise>();
            this.Comment = new HashSet<Comment>();
            this.Room = new HashSet<Room>();
            this.QLHoTroes = new HashSet<QLHoTro>();
            this.QLTDDs = new HashSet<QLTDD>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Roles { get; set; }
    
        public virtual ICollection<Advertise> Advertise { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Room> Room { get; set; }
        public virtual ICollection<QLHoTro> QLHoTroes { get; set; }
        public virtual ICollection<QLTDD> QLTDDs { get; set; }
    }
}
